### ISSUE TITLE
 [开源之旅] 如何从后端开发转型为数据库开发

### ISSUE THREAD

**Issue by ray1888** [xudong963/p-log#1]
之前在Twitter上有关注你，然后现在想从一个GO的后端开发转型去做数据库相关开发（OLAP/OLTP 都可），目前已经在学习的东西：
1. LevelDB（Rust版本已经基本读了，大概IO流程和Compaction 流程都通了）
2. Rust （正在学习中，Trait还不是很熟悉）
3. 看了一些分布式KV如何实现事务的文章

感觉目前真的贡献代码比较少，有什么好的项目可以入手去贡献然后转去做数据库相关的Infra开发呢

**Comment by xudong963** [comment]
Hi @ray1888 

看到你有 go 背景，我建议是做一下 tinysql 和 tinykv，https://github.com/tidb-incubator, 配合这本书: https://book.douban.com/subject/10548379/ ，在这之后差不多就入门了。

另外数据库分为存储层和查询层，做完 tinysql 和 tinykv 之后可以评估一下自己的兴趣点，看看之后着重那一个模块。

关于代码贡献，go 不错的数据库项目有 tidb, cockroach, 但是这两个项目都比较大了，不太好参与进去。rust 不错的有 databend, datafusion, 这两个项目参与哪个看你时间和精力，时间不多的话，可以先试试 datafusion, 上手快。

**Comment by ray1888** [comment]
> 那我先搞搞tinyKV & tinySQL先， databend 也有兴趣，但是要先熟悉SQL 引擎才能去贡献databend吗？如果可以能加微信聊聊么？

**Comment by xudong963** [comment]
@ray1888 也可以在 databend 里面熟悉 SQL 引擎，你 twitter 私我你的微信吧
